### ISSUE TITLE
FB App Error

### ISSUE THREAD

**Issue by rahul286** [chaandsheikh/photohub_rtcamp#1]
Please check

![error](https://cloud.githubusercontent.com/assets/4115/7481760/2432e586-f390-11e4-880d-388174750fc3.png)

**Comment by chaandsheikh** [comment]
I have not made this APP as public, as a result Facebook users I have explicitly added as testers, developers or admin would only able to login into the app.

I have already specified credentials of one Facebook user which is added as a tester. Please use the same for login 

Please check : Assignment notes

Closing the issue
